# Generated by Django 5.1 on 2024-12-03 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('Id_Producto', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('Cantidad_P', models.CharField(max_length=200)),
                ('Tipo_Producto', models.CharField(max_length=300)),
                ('Costo', models.CharField(max_length=10000)),
                ('Fecha_Ingreso', models.DateField()),
                ('Id_Proveedor', models.CharField(max_length=6)),
            ],
        ),
    ]
