# Generated by Django 5.1 on 2024-12-03 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('Id_Venta', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('Id_Nomina', models.CharField(max_length=6)),
                ('Fecha_Venta', models.DateField()),
                ('Id_Empleado', models.CharField(max_length=6)),
                ('Total', models.CharField(max_length=10000)),
                ('Producto_Vendido', models.CharField(max_length=80)),
                ('Cant_Productos', models.CharField(max_length=100)),
                ('Id_Producto', models.CharField(max_length=6)),
                ('Id_Sucursal', models.CharField(max_length=6)),
                ('Id_Proveedor', models.CharField(max_length=6)),
            ],
        ),
    ]
