# Generated by Django 5.1.2 on 2024-11-29 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clientes',
            fields=[
                ('Id_Cliente', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('Nombre', models.CharField(max_length=100)),
                ('Apellido', models.CharField(max_length=100)),
                ('Sexo', models.CharField(max_length=20)),
                ('Direccion', models.CharField(max_length=180)),
                ('Num_Tel', models.CharField(max_length=10)),
                ('Email', models.CharField(max_length=180)),
            ],
        ),
    ]
