# Generated by Django 5.1.2 on 2024-12-02 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sucursal',
            fields=[
                ('Id_Sucursal', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('Locolizacion', models.CharField(max_length=200)),
                ('Num_Empleados', models.CharField(max_length=2)),
                ('Ganancias', models.CharField(max_length=10000)),
                ('Telefono', models.CharField(max_length=10)),
                ('Email', models.CharField(max_length=80)),
                ('Encargado', models.CharField(max_length=20)),
            ],
        ),
    ]
